language: python
dist: xenial
sudo: false
python:
  - '3.5'
  - '3.6'
  - '3.7'
before_install:
  - pip install -U pip
  - pip install python-coveralls
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install
script:
  - poetry run pytest --cov=envtoml
after_success:
  - coveralls
